### ISSUE TITLE
ply requirement

### ISSUE THREAD

**Issue by fnielsen** [neurosynth/neurosynth#51]
Readme.md says ply is optional. Present pip version (0.3.3) needs ply. The present Github requirement.txt has ply. Don't you want install_requires setup from requirements.txt?

**Comment by tyarkoni** [comment]
Thanks for catching this. It *was* optional at some point, but I must have started importing from it in the core dataset module. I don't like to use install_requires, because the dependency list includes packages like scipy, numpy, and pandas that can cause problems/conflicts if installed via vanilla pip. I think the sensible thing to do is either remove ply from both requirements.txt and avoid mandatory imports from it, or remove the "optional" label in the README. I'll probably do the latter, since it's a pretty light dependency.
