### ISSUE TITLE
Some decoding pages point to wrong NeuroVault pages

### ISSUE THREAD

**Issue by chrisfilo** [neurosynth/neurosynth#53]
This page for image 9629 http://neurosynth.org/decode/?neurovault=9629 links back to 8947 (which does not exist) causing a broken link: http://neurovault.org/images/8947/

**Comment by tyarkoni** [comment]
Hmm... that's very weird, since the back-linked image ID comes directly from the NeuroVault API. Is it possible for images to change in NV--e.g., if a user re-uploads the image? I think I'm currently caching decoding requests, so if the image changed, that's probably what happened. If it's not possible for the image to change, I'll look into it--but hard to see what could have happened in that one case given that other images link back okay.

**Comment by chrisfilo** [comment]
I just added this image as a test. The API seems to be giving back the
right URLs http://neurovault.org/api/images/9629/

I am often using this particular image for testing, deleting it afterwards.
Is it possible that you are caching images based on their content?

**Comment by tyarkoni** [comment]
Ah, okay, that explains it. The caching needs to change to check the remote filename, I guess. For now I'll just turn caching off, since I'm under time pressure and resources aren't an issue right now.

**Comment by tyarkoni** [comment]
Okay, fixed. Closing this issue, but will open a separate one to remind myself to change the caching scheme at some point.
