### ISSUE TITLE
feature based clustering returns dense array

### ISSUE THREAD

**Issue by zorro4** [neurosynth/neurosynth#55]
Some possible bugs in the new cluster code I noticed when trying out feature based clustering:

1) get_ids_by_features returns a dense array. Later the magic() code assumes a sparse array, so I added the ability to pass a dense flag to get_ids_by_features. This required changing the dataset. Fixed here: 4483860a4f4966de409c7479ef120e22a193ecf5
2) When outputting the clustering I had to change this line to np.float32 rather than float. Otherwise I got error from nibabel (1.3) saying that the datatype was not recognized

     header.set_data_dtype(np.float32)

By the way, I tried to switch to nibabel 2.x but I keep getting this error I was getting before (which is why I switched back to 1.x) saying __dataobj not found. Any clue what's up with that?

3) Some minor stuff which I'm guessing is just to be implemement but might as well point out
- Why is filename required? Thus far, its not used
- Both the ref and roi data use features, even though cocativation_features is a flag

**Comment by tyarkoni** [comment]
Thanks for the comments!

The get_ids_by_* series of methods are deprecated; you should be using get_studies() for everything, as I'm going to remove the former methods in the next version bump. I suppose we could add a 'dense' argument to get_studies() as well, though it would also be reasonable to keep it as-is and just have to make an extra call to get_image_data(), which *does* have a dense argument.

The clustering code seems to work for me both using the low-level Clusterable API and the magic() function. The test also passes. That said, I haven't tried every possible permutation of arguments. What step is the sparse/dense mismatch happening at? There is some explicit matrix-to-array conversion in the Clusterable class, but I don't see anywhere else where it should be an issue.

I think it's worth considering making nibabel 2.0 a hard dependency, since it broke the 1.3 API in some ways that have already impacted the codebase here. But I guess if that's the extent of the current issues, we're probably okay being inclusive. I'm not sure why you're getting errors with 2.0; I don't have any problems. If you can reliably reproduce the problem, open a separate issue for it. I forget what the dataobj not found thing was about, but I definitely fixed that in a couple of places, and it doesn't seem to occur for me any more.

The filename arg should be used, but I forgot to replace the test image name that's hardcoded. Eep. Will patch that in a second. Ditto for the extra coactivation_features. Thanks!

**Comment by zorro4** [comment]
Ha! I know they're deprecated but you're the one that used it first! 

It was failing in the last line of the Clusterable which has a .toarray() at the end which assumes sparse data, but gets dense data if features is not None. 

I'll try to research the nibabel thing and open a separate issue, but it's come up in two different systems for me, I don't think its just my local install's problem. 

Shall I push my commit that changes that line to np.float32? Probably best to keep it working with 1.x as much as possible, unless it becomes a huge pain.
