### ISSUE TITLE
Fix swagger docs and add alias for v2 API

### ISSUE THREAD

**Issue by KamalakerDadi** [neurosynth/neurosynth#80]
Hello @neurosynth team,

Trying to access http://neurosynth.org/api/v2. Bit, could not found the link to api. Is there any planned maintenance right now ?

Thank you.

**Comment by tyarkoni** [comment]
Ah, thanks for pointing that out. The API itself has moved to just http://neurosynth.org/api/ (I realize it's poor form to break the old API, but...), but it appears the swagger docs aren't displaying following the refactoring. I'll get to that as soon as I can, but it may take a few days.

That said, the syntax should be the same, so if you were making queries successfully before, just removing the `v2` part should fix things. Sorry!

**Comment by tyarkoni** [comment]
Oh, and I'll also add an alias for `v2` so it doesn't break for people (the v1 API wasn't being used by anyone, hence the deprecation).

**Comment by KamalakerDadi** [comment]
Thanks @tyarkoni for looking into this and quick reply.

**Comment by tyarkoni** [comment]
BTW: I talked to Gael at NH18 and it sounded like you guys might be interested in opening a PR for some new functionality. If that's the case (which would be awesome!), let's definitely touch base before that happens, because the entire front-end is very ugly and is going to be replaced with a React-based interface at some point in the next couple of months, so I wouldn't want anyone to duplicate or waste effort.

**Comment by KamalakerDadi** [comment]
I didn't know about that. I will keep this in my mind or may be chat with Gael at some point.
Thanks again.

**Comment by KamalakerDadi** [comment]
Closing as queries are working now as we replaced with http://neurosynth.org/api/decode/

**Comment by KamalakerDadi** [comment]
Any advantage of using with and without ```v2``` ?

**Comment by tyarkoni** [comment]
Absolutely none. Well, I guess without is marginally better, as you won't have the implicit redirection. But it doesn't really matter.
